device_index: 0
width: 640
height: 480
fps: 30
buffer_size: 1

pose_estimation:
  model_complexity: 1
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5

filter:
  type: one_euro
  min_cutoff: 1.0
  beta: 0.007
  d_cutoff: 1.0
